### ISSUE TITLE
Update App Request

### ISSUE THREAD

**Issue by michaelakin** [aws-samples/serverless-dotnet-demo#14]
Please update the app to authenticate with Cognito and verify the authentication using the acesss_token,  in api gateway,  but don't use the Cognito hosted UI to get access tokens.  Write it all in code and use the InitiateAuthAsync cognito call to get tokens.

**Comment by jeastham1993** [comment]
Thanks for the request @michaelakin. The sample application architecture is kept identical across all the different runtimes to give some element of like for like comparison.

Whilst I'd be interested in seeing what latency Cognito adds, that's not what we are looking to do with this repo right now.

Next year, I may look to extend the benchmarks out to different use cases. I'll keep Cognito in mind when it comes to it.

**Comment by michaelakin** [comment]
Yes, thanks I am just experiencing a blocker with Cognito and Auth with API Gateway when not using the Hosted UI (Which my company does not want to use) and wondered if you could find a way around it or raise the issue internally with the Cogntio Team.

**Comment by jeastham1993** [comment]
@michaelakin I can absolutely connect you. Drop me a direct message on of the social media platforms and I can connect you :)
https://www.linkedin.com/in/james-eastham/
