### ISSUE TITLE
NET6TopLevelStatements: Wrong JSON serializer declaration?

### ISSUE THREAD

**Issue by bjorg** [aws-samples/serverless-dotnet-demo#3]
In the `NET6TopLevelStatements` sample, the function for [PutProduct](https://github.com/aws-samples/serverless-dotnet-demo/blob/main/src/NET6TopLevelStatements/PutProduct/Function.cs) there seems to confusion on selecting the correct JSON serializer.

On [line 15](https://github.com/aws-samples/serverless-dotnet-demo/blob/main/src/NET6TopLevelStatements/PutProduct/Function.cs#L15), the assembly attribute declares `SourceGeneratorLambdaJsonSerializer<ApiGatewayProxyJsonSerializerContext>` as the JSON serializer.
```csharp
[assembly: LambdaSerializer(typeof(SourceGeneratorLambdaJsonSerializer<ApiGatewayProxyJsonSerializerContext>))]
```

But then on [line 66-68](https://github.com/aws-samples/serverless-dotnet-demo/blob/main/src/NET6TopLevelStatements/PutProduct/Function.cs#L66), the sample passes in an instance of `DefaultLambdaJsonSerializer` to initialize the Lambda runtime.
```csharp
await LambdaBootstrapBuilder.Create(handler, new DefaultLambdaJsonSerializer())
    .Build()
    .RunAsync();
```

Shouldn't this instead be:
```csharp
await LambdaBootstrapBuilder.Create(handler, new SourceGeneratorLambdaJsonSerializer<ApiGatewayProxyJsonSerializerContext>())
    .Build()
    .RunAsync();
```

Since the JSON serializer is explicitly provided to the Lambda runtime, is line 15 really needed?

**Comment by jeastham1993** [comment]
Hey @bjorg, apologies for missing this! I didn't get a notification from GitHub. You make a really valid point, updating it now.
