### ISSUE TITLE
Don't use PublishAotCompressed

### ISSUE THREAD

**Issue by MichalStrehovsky** [aws-samples/serverless-dotnet-demo#5]
https://github.com/aws-samples/serverless-dotnet-demo/blob/d1da2bf43f29879cc017e626fd72fb339636ea42/src/NET7Native/GetProducts/GetProducts.csproj#L22

This makes startup time worse because the whole program needs to be decompressed first. I don't think there would be benefits for lambdas.

**Comment by smhmhmd** [comment]
@Beau-Gosse-dev is posting an update to remove `PublishAotCompressed`

**Comment by jeastham1993** [comment]
This has been published and merged, thanks for pointing it out @MichalStrehovsky
